#!/usr/bin/env python3

import rospy
from mushr_gprm.planner_node import PlannerROS

if __name__ == "__main__":
    rospy.init_node("planner", anonymous=True)

    PlannerROS(
        num_vertices=rospy.get_param("~num_vertices"),
        connection_radius=float(rospy.get_param("~connection_radius")),
        curvature=float(rospy.get_param("~curvature")),
        tf_prefix=rospy.get_param("~tf_prefix", ""),
    )
    rospy.spin()
